export const docTypes = [
 {id:'application',title:'Application summary',description:'Your completed application or summary sheet.',limit:5,accept:'.pdf',icon:'file'},
 {id:'bank',title:'Bank document',description:'A clear passbook page or cancelled cheque.',limit:2,accept:'.pdf,.jpg,.jpeg,.png',icon:'bank'},
 {id:'academic',title:'Academic record',description:'Your qualifying examination marksheet.',limit:5,accept:'.pdf',icon:'study'},
];
export const samples={application:{name:'Application_Ananya.pdf',size:245760,sample:true},bank:{name:'Passbook_Ananya.pdf',size:614400,sample:true},academic:{name:'Marksheet_Ananya.pdf',size:430080,sample:true}};
export const initialFields={applicationName:'Ananya S. Sharma',applicationId:'DEMO-2026-0142',bankName:'Ananya Sharma',account:'XXXX XXXX 4821',ifsc:'DEMO0000123',academicName:'Ananya S. Sharma',marks:'87.6',roll:'1268?4'};
export function validateFile(file,type){const ext=file.name.split('.').pop().toLowerCase();if(!type.accept.split(',').includes('.'+ext))return 'Choose '+type.accept.replaceAll('.','').toUpperCase()+' files.';if(!file.size)return 'This file is empty. Choose another file.';if(file.size>type.limit*1024*1024)return `Choose a file smaller than ${type.limit} MB.`;return '';}
const normalized=s=>s.toLowerCase().replace(/[.]/g,'').trim().replace(/\s+/g,' ');
export function reviewPacket(files,fields,confirmed){const issues=[];docTypes.forEach(t=>{if(!files[t.id])issues.push({id:'missing-'+t.id,type:'Documents',title:t.title+' is missing',description:'Add this document to complete the demonstration checklist.',doc:t.id,status:'attention'});});if(files.bank&&files.application&&(!fields.bankName.trim()||!fields.applicationName.trim()||normalized(fields.bankName)!==normalized(fields.applicationName)))issues.push({id:'name',type:'Name consistency',title:'A small difference. Worth a second look.',description:'The name in your bank document differs from your application. Check the original documents before submitting.',doc:'bank',status:'attention'});if(files.academic&&(!fields.roll.trim()||fields.roll.includes('?')||!confirmed))issues.push({id:'roll',type:'Legibility',title:'One digit needs your eyes.',description:'Please read the roll number on your marksheet and confirm the complete value.',doc:'academic',status:'review'});return issues;}
